/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as OrganizerIdRouteImport } from './routes/organizer.$id'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as ApiPublicMastodonCallbackRouteImport } from './routes/api/public/mastodon/callback'

const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerIdRoute = OrganizerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrganizerRoute,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMastodonCallbackRoute =
  ApiPublicMastodonCallbackRouteImport.update({
    id: '/api/public/mastodon/callback',
    path: '/api/public/mastodon/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/event/$id': typeof EventIdRoute
  '/organizer/$id': typeof OrganizerIdRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/api/public/mastodon/callback': typeof ApiPublicMastodonCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event/$id': typeof EventIdRoute
  '/organizer/$id': typeof OrganizerIdRoute
  '/organizer': typeof OrganizerIndexRoute
  '/api/public/mastodon/callback': typeof ApiPublicMastodonCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/event/$id': typeof EventIdRoute
  '/organizer/$id': typeof OrganizerIdRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/api/public/mastodon/callback': typeof ApiPublicMastodonCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizer'
    | '/event/$id'
    | '/organizer/$id'
    | '/organizer/'
    | '/api/public/mastodon/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/event/$id'
    | '/organizer/$id'
    | '/organizer'
    | '/api/public/mastodon/callback'
  id:
    | '__root__'
    | '/'
    | '/organizer'
    | '/event/$id'
    | '/organizer/$id'
    | '/organizer/'
    | '/api/public/mastodon/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizerRoute: typeof OrganizerRouteWithChildren
  EventIdRoute: typeof EventIdRoute
  ApiPublicMastodonCallbackRoute: typeof ApiPublicMastodonCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/$id': {
      id: '/organizer/$id'
      path: '/$id'
      fullPath: '/organizer/$id'
      preLoaderRoute: typeof OrganizerIdRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mastodon/callback': {
      id: '/api/public/mastodon/callback'
      path: '/api/public/mastodon/callback'
      fullPath: '/api/public/mastodon/callback'
      preLoaderRoute: typeof ApiPublicMastodonCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrganizerRouteChildren {
  OrganizerIdRoute: typeof OrganizerIdRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
}

const OrganizerRouteChildren: OrganizerRouteChildren = {
  OrganizerIdRoute: OrganizerIdRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
}

const OrganizerRouteWithChildren = OrganizerRoute._addFileChildren(
  OrganizerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizerRoute: OrganizerRouteWithChildren,
  EventIdRoute: EventIdRoute,
  ApiPublicMastodonCallbackRoute: ApiPublicMastodonCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
